// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	errors "github.com/edgexfoundry/go-mod-core-contracts/v3/errors"

	mock "github.com/stretchr/testify/mock"

	responses "github.com/edgexfoundry/go-mod-core-contracts/v3/dtos/responses"
)

// CronTransmissionRecordClient is an autogenerated mock type for the CronTransmissionRecordClient type
type CronTransmissionRecordClient struct {
	mock.Mock
}

// AllCronTransmissionRecords provides a mock function with given fields: ctx, start, end, offset, limit
func (_m *CronTransmissionRecordClient) AllCronTransmissionRecords(ctx context.Context, start int64, end int64, offset int, limit int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX) {
	ret := _m.Called(ctx, start, end, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for AllCronTransmissionRecords")
	}

	var r0 responses.MultiCronTransmissionRecordResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int, int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX)); ok {
		return rf(ctx, start, end, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int, int) responses.MultiCronTransmissionRecordResponse); ok {
		r0 = rf(ctx, start, end, offset, limit)
	} else {
		r0 = ret.Get(0).(responses.MultiCronTransmissionRecordResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int, int) errors.EdgeX); ok {
		r1 = rf(ctx, start, end, offset, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// CronTransmissionRecordsByJobName provides a mock function with given fields: ctx, jobName, start, end, offset, limit
func (_m *CronTransmissionRecordClient) CronTransmissionRecordsByJobName(ctx context.Context, jobName string, start int64, end int64, offset int, limit int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX) {
	ret := _m.Called(ctx, jobName, start, end, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for CronTransmissionRecordsByJobName")
	}

	var r0 responses.MultiCronTransmissionRecordResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int, int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX)); ok {
		return rf(ctx, jobName, start, end, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int, int) responses.MultiCronTransmissionRecordResponse); ok {
		r0 = rf(ctx, jobName, start, end, offset, limit)
	} else {
		r0 = ret.Get(0).(responses.MultiCronTransmissionRecordResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, int, int) errors.EdgeX); ok {
		r1 = rf(ctx, jobName, start, end, offset, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// CronTransmissionRecordsByJobNameAndStatus provides a mock function with given fields: ctx, jobName, status, start, end, offset, limit
func (_m *CronTransmissionRecordClient) CronTransmissionRecordsByJobNameAndStatus(ctx context.Context, jobName string, status string, start int64, end int64, offset int, limit int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX) {
	ret := _m.Called(ctx, jobName, status, start, end, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for CronTransmissionRecordsByJobNameAndStatus")
	}

	var r0 responses.MultiCronTransmissionRecordResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64, int, int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX)); ok {
		return rf(ctx, jobName, status, start, end, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64, int, int) responses.MultiCronTransmissionRecordResponse); ok {
		r0 = rf(ctx, jobName, status, start, end, offset, limit)
	} else {
		r0 = ret.Get(0).(responses.MultiCronTransmissionRecordResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64, int, int) errors.EdgeX); ok {
		r1 = rf(ctx, jobName, status, start, end, offset, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// CronTransmissionRecordsByStatus provides a mock function with given fields: ctx, status, start, end, offset, limit
func (_m *CronTransmissionRecordClient) CronTransmissionRecordsByStatus(ctx context.Context, status string, start int64, end int64, offset int, limit int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX) {
	ret := _m.Called(ctx, status, start, end, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for CronTransmissionRecordsByStatus")
	}

	var r0 responses.MultiCronTransmissionRecordResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int, int) (responses.MultiCronTransmissionRecordResponse, errors.EdgeX)); ok {
		return rf(ctx, status, start, end, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int, int) responses.MultiCronTransmissionRecordResponse); ok {
		r0 = rf(ctx, status, start, end, offset, limit)
	} else {
		r0 = ret.Get(0).(responses.MultiCronTransmissionRecordResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, int, int) errors.EdgeX); ok {
		r1 = rf(ctx, status, start, end, offset, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// NewCronTransmissionRecordClient creates a new instance of CronTransmissionRecordClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCronTransmissionRecordClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CronTransmissionRecordClient {
	mock := &CronTransmissionRecordClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
